on:
    push:
      paths:
        - .github/workflows/build.yml
        - EndlessRunnerGameKit/**
    pull_request_target:
      paths:
        - .github/workflows/build.yml
        - EndlessRunnerGameKit/**
    workflow_dispatch:

jobs:
  unity-build:
    # if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneLinux64
          - StandaloneOSX
          - StandaloneWindows64
    steps:
      - uses: actions/checkout@v4

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: EndlessRunnerGameKit
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: 2021.2.3f1

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-client-unity-${{ matrix.targetPlatform }}-${{ github.sha }}
          path: build/${{ matrix.targetPlatform }}